"""initial catalog moderation models

Revision ID: c279e5cec234
Revises:
Create Date: 2026-06-23 22:23:33.261656+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "c279e5cec234"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_categories_slug"), "categories", ["slug"], unique=True)
    op.create_table(
        "reference_entities",
        sa.Column(
            "type",
            sa.Enum(
                "manufacturer",
                "publisher",
                "franchise",
                "character",
                "author",
                "series",
                name="reference_type",
            ),
            nullable=False,
        ),
        sa.Column("canonical_name", sa.String(length=255), nullable=False),
        sa.Column("normalized_name", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("type", "normalized_name", name="uq_reference_type_normalized_name"),
    )
    op.create_index(
        op.f("ix_reference_entities_normalized_name"),
        "reference_entities",
        ["normalized_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reference_entities_type"), "reference_entities", ["type"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum("user", "moderator", "senior_moderator", "admin", name="user_role"),
            server_default="user",
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "attribute_definitions",
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "value_type",
            sa.Enum(
                "text",
                "integer",
                "decimal",
                "boolean",
                "date",
                "reference",
                name="attribute_value_type",
            ),
            nullable=False,
        ),
        sa.Column("is_required", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_filterable", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_searchable", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_variant_attribute", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("validation_rules", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("category_id", "code", name="uq_attribute_definition_category_code"),
    )
    op.create_index(
        op.f("ix_attribute_definitions_category_id"),
        "attribute_definitions",
        ["category_id"],
        unique=False,
    )
    op.create_table(
        "catalog_items",
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("canonical_title", sa.String(length=500), nullable=False),
        sa.Column("normalized_title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("release_year", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("draft", "active", "archived", name="catalog_status"),
            server_default="active",
            nullable=False,
        ),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column("updated_by_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_catalog_items_canonical_title"), "catalog_items", ["canonical_title"], unique=False
    )
    op.create_index(
        op.f("ix_catalog_items_category_id"), "catalog_items", ["category_id"], unique=False
    )
    op.create_index(
        op.f("ix_catalog_items_normalized_title"),
        "catalog_items",
        ["normalized_title"],
        unique=False,
    )
    op.create_table(
        "collections",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "visibility",
            sa.Enum("private", "unlisted", "public", name="collection_visibility"),
            server_default="private",
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "name", name="uq_collection_owner_name"),
    )
    op.create_index(op.f("ix_collections_owner_id"), "collections", ["owner_id"], unique=False)
    op.create_table(
        "reference_aliases",
        sa.Column("reference_id", sa.Uuid(), nullable=False),
        sa.Column("alias", sa.String(length=255), nullable=False),
        sa.Column("normalized_alias", sa.String(length=255), nullable=False),
        sa.Column("language", sa.String(length=10), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["reference_id"], ["reference_entities.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("reference_id", "normalized_alias", name="uq_reference_alias"),
    )
    op.create_index(
        op.f("ix_reference_aliases_normalized_alias"),
        "reference_aliases",
        ["normalized_alias"],
        unique=False,
    )
    op.create_table(
        "catalog_item_attributes",
        sa.Column("catalog_item_id", sa.Uuid(), nullable=False),
        sa.Column("attribute_definition_id", sa.Uuid(), nullable=False),
        sa.Column("value_text", sa.String(length=1000), nullable=True),
        sa.Column("value_integer", sa.Integer(), nullable=True),
        sa.Column("value_decimal", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("value_boolean", sa.Boolean(), nullable=True),
        sa.Column("value_date", sa.Date(), nullable=True),
        sa.Column("reference_entity_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attribute_definition_id"],
            ["attribute_definitions.id"],
        ),
        sa.ForeignKeyConstraint(["catalog_item_id"], ["catalog_items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["reference_entity_id"],
            ["reference_entities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "catalog_item_id", "attribute_definition_id", name="uq_catalog_item_attribute"
        ),
    )
    op.create_index(
        op.f("ix_catalog_item_attributes_attribute_definition_id"),
        "catalog_item_attributes",
        ["attribute_definition_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_catalog_item_attributes_catalog_item_id"),
        "catalog_item_attributes",
        ["catalog_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_catalog_item_attributes_reference_entity_id"),
        "catalog_item_attributes",
        ["reference_entity_id"],
        unique=False,
    )
    op.create_table(
        "catalog_variants",
        sa.Column("catalog_item_id", sa.Uuid(), nullable=False),
        sa.Column("canonical_title", sa.String(length=500), nullable=False),
        sa.Column("normalized_title", sa.String(length=500), nullable=False),
        sa.Column("sku", sa.String(length=100), nullable=True),
        sa.Column("barcode", sa.String(length=100), nullable=True),
        sa.Column("release_date", sa.Date(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("draft", "active", "archived", name="catalog_status"),
            server_default="active",
            nullable=False,
        ),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column("updated_by_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["catalog_item_id"], ["catalog_items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_catalog_variants_barcode"), "catalog_variants", ["barcode"], unique=False
    )
    op.create_index(
        op.f("ix_catalog_variants_canonical_title"),
        "catalog_variants",
        ["canonical_title"],
        unique=False,
    )
    op.create_index(
        op.f("ix_catalog_variants_catalog_item_id"),
        "catalog_variants",
        ["catalog_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_catalog_variants_normalized_title"),
        "catalog_variants",
        ["normalized_title"],
        unique=False,
    )
    op.create_index(op.f("ix_catalog_variants_sku"), "catalog_variants", ["sku"], unique=False)
    op.create_index(
        "uq_catalog_variants_barcode_not_null",
        "catalog_variants",
        ["barcode"],
        unique=True,
        postgresql_where=sa.text("barcode IS NOT NULL"),
    )
    op.create_index(
        "uq_catalog_variants_sku_not_null",
        "catalog_variants",
        ["sku"],
        unique=True,
        postgresql_where=sa.text("sku IS NOT NULL"),
    )
    op.create_table(
        "catalog_aliases",
        sa.Column("catalog_item_id", sa.Uuid(), nullable=True),
        sa.Column("catalog_variant_id", sa.Uuid(), nullable=True),
        sa.Column("alias", sa.String(length=500), nullable=False),
        sa.Column("normalized_alias", sa.String(length=500), nullable=False),
        sa.Column("language", sa.String(length=10), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            """
            (
                catalog_item_id IS NOT NULL
                AND catalog_variant_id IS NULL
            )
            OR
            (
                catalog_item_id IS NULL
                AND catalog_variant_id IS NOT NULL
            )
            """,
            name="ck_catalog_alias_single_owner",
        ),
        sa.ForeignKeyConstraint(["catalog_item_id"], ["catalog_items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["catalog_variant_id"], ["catalog_variants.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_catalog_aliases_catalog_item_id"),
        "catalog_aliases",
        ["catalog_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_catalog_aliases_catalog_variant_id"),
        "catalog_aliases",
        ["catalog_variant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_catalog_aliases_normalized_alias"),
        "catalog_aliases",
        ["normalized_alias"],
        unique=False,
    )
    op.create_table(
        "catalog_requests",
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("raw_title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("source_url", sa.String(length=2000), nullable=True),
        sa.Column("proposed_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "in_review",
                "needs_information",
                "approved",
                "rejected",
                "duplicate",
                "cancelled",
                name="catalog_request_status",
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("assigned_to_id", sa.Uuid(), nullable=True),
        sa.Column("moderated_by_id", sa.Uuid(), nullable=True),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("approved_catalog_item_id", sa.Uuid(), nullable=True),
        sa.Column("approved_variant_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["approved_catalog_item_id"],
            ["catalog_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["approved_variant_id"],
            ["catalog_variants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["assigned_to_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["moderated_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_catalog_requests_category_id"), "catalog_requests", ["category_id"], unique=False
    )
    op.create_index(
        op.f("ix_catalog_requests_created_by_id"),
        "catalog_requests",
        ["created_by_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_catalog_requests_status"), "catalog_requests", ["status"], unique=False
    )
    op.create_table(
        "catalog_variant_attributes",
        sa.Column("catalog_variant_id", sa.Uuid(), nullable=False),
        sa.Column("attribute_definition_id", sa.Uuid(), nullable=False),
        sa.Column("value_text", sa.String(length=1000), nullable=True),
        sa.Column("value_integer", sa.Integer(), nullable=True),
        sa.Column("value_decimal", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("value_boolean", sa.Boolean(), nullable=True),
        sa.Column("value_date", sa.Date(), nullable=True),
        sa.Column("reference_entity_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attribute_definition_id"],
            ["attribute_definitions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["catalog_variant_id"], ["catalog_variants.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["reference_entity_id"],
            ["reference_entities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "catalog_variant_id", "attribute_definition_id", name="uq_catalog_variant_attribute"
        ),
    )
    op.create_index(
        op.f("ix_catalog_variant_attributes_attribute_definition_id"),
        "catalog_variant_attributes",
        ["attribute_definition_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_catalog_variant_attributes_catalog_variant_id"),
        "catalog_variant_attributes",
        ["catalog_variant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_catalog_variant_attributes_reference_entity_id"),
        "catalog_variant_attributes",
        ["reference_entity_id"],
        unique=False,
    )
    op.create_table(
        "collection_items",
        sa.Column("collection_id", sa.Uuid(), nullable=False),
        sa.Column("catalog_variant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "condition",
            sa.Enum("sealed", "new", "opened", "used", "damaged", name="item_condition"),
            nullable=True,
        ),
        sa.Column("quantity", sa.Integer(), server_default="1", nullable=False),
        sa.Column("purchase_price", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("purchase_currency", sa.String(length=3), nullable=True),
        sa.Column("purchase_date", sa.Date(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["catalog_variant_id"],
            ["catalog_variants.id"],
        ),
        sa.ForeignKeyConstraint(["collection_id"], ["collections.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_collection_items_catalog_variant_id"),
        "collection_items",
        ["catalog_variant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_collection_items_collection_id"),
        "collection_items",
        ["collection_id"],
        unique=False,
    )
    op.create_table(
        "moderation_actions",
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("moderator_id", sa.Uuid(), nullable=False),
        sa.Column(
            "action",
            sa.Enum(
                "assign",
                "approve",
                "reject",
                "mark_duplicate",
                "request_information",
                "edit",
                name="moderation_action_type",
            ),
            nullable=False,
        ),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["moderator_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["request_id"], ["catalog_requests.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_moderation_actions_moderator_id"),
        "moderation_actions",
        ["moderator_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_moderation_actions_request_id"), "moderation_actions", ["request_id"], unique=False
    )
    op.create_table(
        "wishlist_items",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("catalog_variant_id", sa.Uuid(), nullable=True),
        sa.Column("catalog_request_id", sa.Uuid(), nullable=True),
        sa.Column("target_price", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("source_url", sa.String(length=2000), nullable=True),
        sa.Column("priority", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "pending_moderation",
                "rejected",
                "purchased",
                "archived",
                name="wishlist_status",
            ),
            server_default="active",
            nullable=False,
        ),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            """
            (
                catalog_variant_id IS NOT NULL
                AND catalog_request_id IS NULL
            )
            OR
            (
                catalog_variant_id IS NULL
                AND catalog_request_id IS NOT NULL
            )
            """,
            name="ck_wishlist_catalog_or_request",
        ),
        sa.ForeignKeyConstraint(
            ["catalog_request_id"],
            ["catalog_requests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["catalog_variant_id"],
            ["catalog_variants.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_wishlist_items_catalog_request_id"),
        "wishlist_items",
        ["catalog_request_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wishlist_items_catalog_variant_id"),
        "wishlist_items",
        ["catalog_variant_id"],
        unique=False,
    )
    op.create_index(op.f("ix_wishlist_items_user_id"), "wishlist_items", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_wishlist_items_user_id"), table_name="wishlist_items")
    op.drop_index(op.f("ix_wishlist_items_catalog_variant_id"), table_name="wishlist_items")
    op.drop_index(op.f("ix_wishlist_items_catalog_request_id"), table_name="wishlist_items")
    op.drop_table("wishlist_items")
    op.drop_index(op.f("ix_moderation_actions_request_id"), table_name="moderation_actions")
    op.drop_index(op.f("ix_moderation_actions_moderator_id"), table_name="moderation_actions")
    op.drop_table("moderation_actions")
    op.drop_index(op.f("ix_collection_items_collection_id"), table_name="collection_items")
    op.drop_index(op.f("ix_collection_items_catalog_variant_id"), table_name="collection_items")
    op.drop_table("collection_items")
    op.drop_index(
        op.f("ix_catalog_variant_attributes_reference_entity_id"),
        table_name="catalog_variant_attributes",
    )
    op.drop_index(
        op.f("ix_catalog_variant_attributes_catalog_variant_id"),
        table_name="catalog_variant_attributes",
    )
    op.drop_index(
        op.f("ix_catalog_variant_attributes_attribute_definition_id"),
        table_name="catalog_variant_attributes",
    )
    op.drop_table("catalog_variant_attributes")
    op.drop_index(op.f("ix_catalog_requests_status"), table_name="catalog_requests")
    op.drop_index(op.f("ix_catalog_requests_created_by_id"), table_name="catalog_requests")
    op.drop_index(op.f("ix_catalog_requests_category_id"), table_name="catalog_requests")
    op.drop_table("catalog_requests")
    op.drop_index(op.f("ix_catalog_aliases_normalized_alias"), table_name="catalog_aliases")
    op.drop_index(op.f("ix_catalog_aliases_catalog_variant_id"), table_name="catalog_aliases")
    op.drop_index(op.f("ix_catalog_aliases_catalog_item_id"), table_name="catalog_aliases")
    op.drop_table("catalog_aliases")
    op.drop_index(
        "uq_catalog_variants_sku_not_null",
        table_name="catalog_variants",
        postgresql_where=sa.text("sku IS NOT NULL"),
    )
    op.drop_index(
        "uq_catalog_variants_barcode_not_null",
        table_name="catalog_variants",
        postgresql_where=sa.text("barcode IS NOT NULL"),
    )
    op.drop_index(op.f("ix_catalog_variants_sku"), table_name="catalog_variants")
    op.drop_index(op.f("ix_catalog_variants_normalized_title"), table_name="catalog_variants")
    op.drop_index(op.f("ix_catalog_variants_catalog_item_id"), table_name="catalog_variants")
    op.drop_index(op.f("ix_catalog_variants_canonical_title"), table_name="catalog_variants")
    op.drop_index(op.f("ix_catalog_variants_barcode"), table_name="catalog_variants")
    op.drop_table("catalog_variants")
    op.drop_index(
        op.f("ix_catalog_item_attributes_reference_entity_id"), table_name="catalog_item_attributes"
    )
    op.drop_index(
        op.f("ix_catalog_item_attributes_catalog_item_id"), table_name="catalog_item_attributes"
    )
    op.drop_index(
        op.f("ix_catalog_item_attributes_attribute_definition_id"),
        table_name="catalog_item_attributes",
    )
    op.drop_table("catalog_item_attributes")
    op.drop_index(op.f("ix_reference_aliases_normalized_alias"), table_name="reference_aliases")
    op.drop_table("reference_aliases")
    op.drop_index(op.f("ix_collections_owner_id"), table_name="collections")
    op.drop_table("collections")
    op.drop_index(op.f("ix_catalog_items_normalized_title"), table_name="catalog_items")
    op.drop_index(op.f("ix_catalog_items_category_id"), table_name="catalog_items")
    op.drop_index(op.f("ix_catalog_items_canonical_title"), table_name="catalog_items")
    op.drop_table("catalog_items")
    op.drop_index(op.f("ix_attribute_definitions_category_id"), table_name="attribute_definitions")
    op.drop_table("attribute_definitions")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_reference_entities_type"), table_name="reference_entities")
    op.drop_index(op.f("ix_reference_entities_normalized_name"), table_name="reference_entities")
    op.drop_table("reference_entities")
    op.drop_index(op.f("ix_categories_slug"), table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
